### ISSUE TITLE
Styles does not match

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#59]
Please refer to the next image: 

![screen shot 2015-12-14 at 07 19 47](https://cloud.githubusercontent.com/assets/3921289/11781947/3ef1b756-a233-11e5-8cf2-18f7ff83cd6f.png)

The `<- Previous Page` and the `Post Comment` has two different hover styles, please match all the styles to follow the same as `Post comment` button instead.

**Comment by jrrrsmith** [comment]
Hey @nucro the hover states of the buttons are animating at different speeds, you can see here below in these images.

the prev and next buttons animate at .4s and the Post Comment button animates at .25s

Please make the animation times consistent, I think .4s looks best but that's up to you guys.

Thanks

![screen shot 2015-12-15 at 11 06 01 am](https://cloud.githubusercontent.com/assets/7597286/11815883/dd540190-a31b-11e5-9a8b-ec8bb2363e4e.png)

![screen shot 2015-12-15 at 11 06 29 am](https://cloud.githubusercontent.com/assets/7597286/11815904/ef2e2e22-a31b-11e5-8dd7-d831206a7cf2.png)

**Comment by jrrrsmith** [comment]
@nucro thanks for taking care of the transition times for the hover state.

I noticed a couple things about the Prev and Next buttons when I was reviewing the site.  These buttons have an opacity of .6 set on them.  I think we should just have an opacity of 1 so that they look like the Post Comment button.  All buttons on the site shouldn't have an opacity less than 1.  Unless this is something that was decided by you and @mitogh ?

Another thing, the focus selector for the buttons has a transform property of translatey: 5px. Its a little weird, you click on it and it moves down 5px.  Any reason for this?  Please remove that as well, again unless this is a design feature that was discussed and I'm just unaware.

Thanks.

please see the pic below for a reference:

![screen shot 2015-12-16 at 1 28 32 pm](https://cloud.githubusercontent.com/assets/7597286/11850176/b67df4ca-a3f9-11e5-9b2f-4d12439ee06e.png)

**Comment by mitogh** [comment]
@nucro do you have any comments or fix for this comments made by @jrrrsmith ?

**Comment by orcunilbeyli** [comment]
@jrrrsmith sorry for late answer. I want to give a feel of "pushing button" to this button actually. What do you think @mitogh ?

**Comment by mitogh** [comment]
Well in my opinion consistency it's better for UI if you are going to do a change like that apply that change everywhere @nucro you can't do it only on some places.

**Comment by orcunilbeyli** [comment]
So do you think should I remove it or apply it to everywhere? I mean every buttons ofc.

**Comment by mitogh** [comment]
Remove it please and try to keep things simple this feature it was supposed to be pretty straightforward, no new features, on this please for any new feature, enhancement open an issue to discuss before that, I would like to finish this style release today.

**Comment by orcunilbeyli** [comment]
On it.

**Comment by orcunilbeyli** [comment]
I also think it'd be better to remove background color of prev/next buttons. Make them more link-ish. @mitogh ?

**Comment by mitogh** [comment]
Ok I agree :+1:

**Comment by mitogh** [comment]
Let me know once the changes are on the branch @nucro

**Comment by orcunilbeyli** [comment]
Changes on the branch @mitogh .I also created a new issue. Check #62
